# Generated by Django 3.2.8 on 2021-10-11 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Category name.', max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Set a name for exam.', max_length=250, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Set a duration of an exam.', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of an exam.', max_length=1000, null=True)),
                ('author', models.ForeignKey(help_text='Author of an exam.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Set the category for an exam.', null='true', on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam', to='exam.category')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
    ]
