# Generated by Django 3.2.8 on 2021-10-11 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import questions.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Question text.', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when question was created')),
                ('difficulty', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=(5, 5), help_text='Choose the difficulty of the question')),
                ('author', models.ForeignKey(help_text='Author of the question.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Category of question.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.category')),
                ('exam', models.ForeignKey(help_text='List of questions for this exam.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='exam.exam')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, help_text='Choice body', max_length=500, null=True)),
                ('image', models.ImageField(blank=True, help_text='Choose image', null=True, upload_to=questions.utils.path_and_rename)),
                ('right_answer', models.BooleanField(default=False, help_text='Check the right answer', null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='questions.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
