# Generated by Django 3.2.8 on 2021-10-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of question.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='List of questions for this exam.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='exam.exam'),
        ),
    ]
