version: "3.9"
services:
  backend:
    build: .
    volumes:
      - .:/django-backend
    ports:
      - '8000:8000'
    image: backend:django-backend
    container_name: django-backend
    restart: always
    command: >
      bash -c "pip install -r requirements.txt
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn quizz_backend.wsgi --bind 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgresql-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    ports:
      - '5050:80'
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-setup.config:/etc/nginx/conf.d/default.conf:ro
      - ./django-backend/staticfiles:/static
    depends_on:
      - backend
      - pgadmin